// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderService.Infrastructure.Models
{
    public partial class SP_CreateReturnRequestResult
    {
        public Guid? ReturnId { get; set; }
        [StringLength(50)]
        public string ReturnNumber { get; set; }
        [StringLength(7)]
        public string Status { get; set; }
        [StringLength(35)]
        public string Message { get; set; }
    }
}
