// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderService.Infrastructure.Models
{
    public partial class SP_GetOrderDetailsResult
    {
        public Guid OrderId { get; set; }
        [StringLength(50)]
        public string OrderNumber { get; set; }
        public Guid CustomerId { get; set; }
        public Guid? CartId { get; set; }
        [StringLength(50)]
        public string OrderStatus { get; set; }
        [StringLength(50)]
        public string OrderType { get; set; }
        [StringLength(50)]
        public string OrderSource { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime? ConfirmedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
        public DateTime? CancelledAt { get; set; }
        [Column("SubtotalAmount", TypeName = "decimal(18,4)")]
        public decimal SubtotalAmount { get; set; }
        [Column("DiscountAmount", TypeName = "decimal(18,4)")]
        public decimal DiscountAmount { get; set; }
        [Column("TaxAmount", TypeName = "decimal(18,4)")]
        public decimal TaxAmount { get; set; }
        [Column("ShippingAmount", TypeName = "decimal(18,4)")]
        public decimal ShippingAmount { get; set; }
        [Column("AdjustmentAmount", TypeName = "decimal(18,4)")]
        public decimal AdjustmentAmount { get; set; }
        [Column("TotalAmount", TypeName = "decimal(18,4)")]
        public decimal TotalAmount { get; set; }
        [StringLength(3)]
        public string CurrencyCode { get; set; }
        [Column("ExchangeRate", TypeName = "decimal(18,6)")]
        public decimal ExchangeRate { get; set; }
        [StringLength(50)]
        public string PaymentStatus { get; set; }
        [StringLength(50)]
        public string FulfillmentStatus { get; set; }
        [StringLength(255)]
        public string CustomerEmail { get; set; }
        [StringLength(50)]
        public string CustomerPhone { get; set; }
        [StringLength(45)]
        public string IPAddress { get; set; }
        [StringLength(500)]
        public string UserAgent { get; set; }
        public bool IsGuestCheckout { get; set; }
        [StringLength(20)]
        public string Priority { get; set; }
        [StringLength(2147483647)]
        public string InternalNotes { get; set; }
        [StringLength(2147483647)]
        public string CustomerNotes { get; set; }
        [StringLength(2147483647)]
        public string Tags { get; set; }
        public byte[] RowVersion { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
