// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderService.Infrastructure.Models
{
    public partial class SP_PerformFraudCheckResult
    {
        public Guid? FraudCheckId { get; set; }
        [Column("RiskScore", TypeName = "decimal(5,2)")]
        public decimal? RiskScore { get; set; }
        [StringLength(20)]
        public string RiskLevel { get; set; }
        [StringLength(50)]
        public string RecommendedAction { get; set; }
        [StringLength(7)]
        public string Status { get; set; }
    }
}
