// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderLoyaltyPoint
{
    public Guid LoyaltyPointId { get; set; }

    public Guid OrderId { get; set; }

    public Guid CustomerId { get; set; }

    public int PointsEarned { get; set; }

    public int PointsRedeemed { get; set; }

    public decimal PointValue { get; set; }

    public string TransactionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}