// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderCancellation
{
    public Guid CancellationId { get; set; }

    public Guid OrderId { get; set; }

    public string CancellationType { get; set; }

    public string CancellationReason { get; set; }

    public Guid? CancelledBy { get; set; }

    public string CancelledByType { get; set; }

    public DateTime CancelledAt { get; set; }

    public bool RefundInitiated { get; set; }

    public decimal RefundAmount { get; set; }

    public decimal CancellationFee { get; set; }

    public bool CustomerNotified { get; set; }

    public string Notes { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}