// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderReturnItem
{
    public Guid ReturnItemId { get; set; }

    public Guid ReturnId { get; set; }

    public Guid OrderItemId { get; set; }

    public int ReturnQuantity { get; set; }

    public string ReturnReason { get; set; }

    public string ItemCondition { get; set; }

    public decimal RefundAmount { get; set; }

    public decimal RestockingFee { get; set; }

    public bool IsApproved { get; set; }

    public string InspectionNotes { get; set; }

    public string DispositionAction { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual OrderReturn Return { get; set; }
}