// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderDocument
{
    public Guid DocumentId { get; set; }

    public Guid OrderId { get; set; }

    public string DocumentType { get; set; }

    public string DocumentUrl { get; set; }

    public string DocumentNumber { get; set; }

    public DateTime GeneratedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string FileFormat { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}