// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderTimeline
{
    public Guid TimelineId { get; set; }

    public Guid OrderId { get; set; }

    public string EventType { get; set; }

    public string EventDescription { get; set; }

    public DateTime EventDate { get; set; }

    public bool IsVisibleToCustomer { get; set; }

    public string Icon { get; set; }

    public string Metadata { get; set; }

    public virtual Order Order { get; set; }
}