// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderDiscount
{
    public Guid OrderDiscountId { get; set; }

    public Guid OrderId { get; set; }

    public Guid? OrderItemId { get; set; }

    public string DiscountType { get; set; }

    public string CouponCode { get; set; }

    public Guid? PromotionId { get; set; }

    public string DiscountName { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? DiscountPercentage { get; set; }

    public DateTime AppliedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}