// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderHold
{
    public Guid HoldId { get; set; }

    public Guid OrderId { get; set; }

    public string HoldType { get; set; }

    public string HoldReason { get; set; }

    public string HoldStatus { get; set; }

    public Guid? PlacedBy { get; set; }

    public DateTime PlacedAt { get; set; }

    public Guid? ReleasedBy { get; set; }

    public DateTime? ReleasedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string Notes { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }
}