// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderShipmentItem
{
    public Guid ShipmentItemId { get; set; }

    public Guid ShipmentId { get; set; }

    public Guid OrderItemId { get; set; }

    public int Quantity { get; set; }

    public string SerialNumbers { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual OrderShipment Shipment { get; set; }
}