// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderNote
{
    public Guid OrderNoteId { get; set; }

    public Guid OrderId { get; set; }

    public string NoteType { get; set; }

    public string Note { get; set; }

    public bool IsVisibleToCustomer { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}