// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderPayment
{
    public Guid OrderPaymentId { get; set; }

    public Guid OrderId { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentProvider { get; set; }

    public string TransactionId { get; set; }

    public string PaymentStatus { get; set; }

    public decimal Amount { get; set; }

    public decimal RefundedAmount { get; set; }

    public string CurrencyCode { get; set; }

    public string AuthorizationCode { get; set; }

    public string CardType { get; set; }

    public string CardLastFour { get; set; }

    public int? CardExpiryMonth { get; set; }

    public int? CardExpiryYear { get; set; }

    public DateTime? PaymentDate { get; set; }

    public DateTime? AuthorizedAt { get; set; }

    public DateTime? CapturedAt { get; set; }

    public DateTime? RefundedAt { get; set; }

    public string PaymentGatewayResponse { get; set; }

    public bool IsRecurring { get; set; }

    public decimal? RiskScore { get; set; }

    public string ThreeDsecureStatus { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderRefund> OrderRefunds { get; set; } = new List<OrderRefund>();
}