// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderShipment
{
    public Guid ShipmentId { get; set; }

    public Guid OrderId { get; set; }

    public string ShipmentNumber { get; set; }

    public Guid? WarehouseId { get; set; }

    public string ShipmentStatus { get; set; }

    public string ShippingMethod { get; set; }

    public string CarrierName { get; set; }

    public string CarrierCode { get; set; }

    public string ServiceType { get; set; }

    public string TrackingNumber { get; set; }

    public string TrackingUrl { get; set; }

    public decimal ShippingCost { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public decimal? PackageWeight { get; set; }

    public string PackageDimensions { get; set; }

    public int PackageCount { get; set; }

    public string LabelUrl { get; set; }

    public bool SignatureRequired { get; set; }

    public string DeliverySignature { get; set; }

    public string DeliveryProofImage { get; set; }

    public string DeliveryInstructions { get; set; }

    public int DeliveryAttempts { get; set; }

    public DateTime? LastAttemptDate { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderShipmentItem> OrderShipmentItems { get; set; } = new List<OrderShipmentItem>();
}