// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderReturn
{
    public Guid ReturnId { get; set; }

    public Guid OrderId { get; set; }

    public string ReturnNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string ReturnStatus { get; set; }

    public string ReturnType { get; set; }

    public string ReturnReason { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public decimal RefundAmount { get; set; }

    public decimal RestockingFee { get; set; }

    public decimal ReturnShippingCost { get; set; }

    public string CustomerComments { get; set; }

    public string InternalNotes { get; set; }

    public string ReturnShippingLabel { get; set; }

    public string ReturnTrackingNumber { get; set; }

    public string QualityCheckStatus { get; set; }

    public string QualityCheckNotes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderRefund> OrderRefunds { get; set; } = new List<OrderRefund>();

    public virtual ICollection<OrderReturnItem> OrderReturnItems { get; set; } = new List<OrderReturnItem>();
}