// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderFulfillmentAssignment
{
    public Guid AssignmentId { get; set; }

    public Guid OrderId { get; set; }

    public Guid OrderItemId { get; set; }

    public Guid WarehouseId { get; set; }

    public string AssignmentStatus { get; set; }

    public DateTime AssignedAt { get; set; }

    public Guid? PickedBy { get; set; }

    public DateTime? PickedAt { get; set; }

    public Guid? PackedBy { get; set; }

    public DateTime? PackedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}