// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderRefund
{
    public Guid RefundId { get; set; }

    public Guid OrderId { get; set; }

    public Guid? ReturnId { get; set; }

    public Guid? OrderPaymentId { get; set; }

    public string RefundNumber { get; set; }

    public string RefundStatus { get; set; }

    public string RefundType { get; set; }

    public string RefundMethod { get; set; }

    public decimal RefundAmount { get; set; }

    public string RefundReason { get; set; }

    public string TransactionId { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderPayment OrderPayment { get; set; }

    public virtual OrderReturn Return { get; set; }
}