// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderItemOption
{
    public Guid OrderItemOptionId { get; set; }

    public Guid OrderItemId { get; set; }

    public string OptionName { get; set; }

    public string OptionValue { get; set; }

    public decimal PriceAdjustment { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}