// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderAdjustment
{
    public Guid AdjustmentId { get; set; }

    public Guid OrderId { get; set; }

    public string AdjustmentType { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public Guid? AppliedBy { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}