// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderStatusHistory
{
    public Guid StatusHistoryId { get; set; }

    public Guid OrderId { get; set; }

    public string FromStatus { get; set; }

    public string ToStatus { get; set; }

    public Guid? ChangedBy { get; set; }

    public string ChangeReason { get; set; }

    public string Notes { get; set; }

    public bool IsCustomerNotified { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual Order Order { get; set; }
}