// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderTaxis
{
    public Guid OrderTaxId { get; set; }

    public Guid OrderId { get; set; }

    public Guid? OrderItemId { get; set; }

    public string TaxType { get; set; }

    public string TaxName { get; set; }

    public decimal TaxRate { get; set; }

    public decimal TaxAmount { get; set; }

    public string TaxJurisdiction { get; set; }

    public string TaxCalculationMethod { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}