// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderFraudCheck
{
    public Guid FraudCheckId { get; set; }

    public Guid OrderId { get; set; }

    public string FraudProvider { get; set; }

    public decimal RiskScore { get; set; }

    public string RiskLevel { get; set; }

    public string CheckStatus { get; set; }

    public string FraudIndicators { get; set; }

    public string RecommendedAction { get; set; }

    public Guid? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string ReviewNotes { get; set; }

    public DateTime CheckedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}