// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderMetric
{
    public Guid MetricId { get; set; }

    public Guid OrderId { get; set; }

    public int? TimeToConfirmation { get; set; }

    public int? TimeToFirstShipment { get; set; }

    public int? TimeToFullFulfillment { get; set; }

    public int? TimeToDelivery { get; set; }

    public decimal? CustomerLifetimeValue { get; set; }

    public bool IsRepeatCustomer { get; set; }

    public decimal? OrderProcessingCost { get; set; }

    public decimal? ProfitMargin { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }
}