// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderGiftCard
{
    public Guid GiftCardId { get; set; }

    public Guid OrderId { get; set; }

    public string GiftCardCode { get; set; }

    public decimal InitialAmount { get; set; }

    public decimal AppliedAmount { get; set; }

    public decimal RemainingBalance { get; set; }

    public DateTime AppliedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}