// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderAddress
{
    public Guid OrderAddressId { get; set; }

    public Guid OrderId { get; set; }

    public string AddressType { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CompanyName { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string StateProvince { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public bool IsValidated { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}