// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OrderSubscription
{
    public Guid SubscriptionId { get; set; }

    public Guid OrderId { get; set; }

    public Guid CustomerId { get; set; }

    public string SubscriptionStatus { get; set; }

    public string Frequency { get; set; }

    public DateTime? NextOrderDate { get; set; }

    public DateTime? LastOrderDate { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? TotalOccurrences { get; set; }

    public int CompletedOccurrences { get; set; }

    public bool IsAutoRenew { get; set; }

    public Guid? PaymentMethodId { get; set; }

    public byte[] RowVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }
}