// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class OutboxMessage
{
    public Guid OutboxMessageId { get; set; }

    public string AggregateType { get; set; }

    public Guid AggregateId { get; set; }

    public string EventType { get; set; }

    public int EventVersion { get; set; }

    public string Payload { get; set; }

    public DateTime OccurredAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public int RetryCount { get; set; }

    public string LastError { get; set; }

    public byte[] RowVersion { get; set; }
}