// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwCustomerOrderHistory
{
    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public int? TotalOrders { get; set; }

    public decimal? TotalSpent { get; set; }

    public decimal? AverageOrderValue { get; set; }

    public DateTime? LastOrderDate { get; set; }

    public DateTime? FirstOrderDate { get; set; }

    public int? CompletedOrders { get; set; }

    public int? CancelledOrders { get; set; }

    public string CustomerSegment { get; set; }
}