// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwDailyOrderMetric
{
    public DateOnly? OrderDay { get; set; }

    public int? TotalOrders { get; set; }

    public decimal? TotalRevenue { get; set; }

    public decimal? AverageOrderValue { get; set; }

    public int? CompletedOrders { get; set; }

    public int? CancelledOrders { get; set; }

    public int? SubscriptionOrders { get; set; }

    public decimal? CancellationRate { get; set; }
}