// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwFraudRiskDashboard
{
    public Guid FraudCheckId { get; set; }

    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal RiskScore { get; set; }

    public string RiskLevel { get; set; }

    public string CheckStatus { get; set; }

    public string RecommendedAction { get; set; }

    public Guid? ReviewedBy { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public DateTime CheckedAt { get; set; }

    public string FraudStatus { get; set; }

    public int? HoursPendingReview { get; set; }
}