// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwOrderSummary
{
    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentStatus { get; set; }

    public string FulfillmentStatus { get; set; }

    public string OrderType { get; set; }

    public string OrderSource { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? ConfirmedAt { get; set; }

    public decimal TotalAmount { get; set; }

    public string CurrencyCode { get; set; }

    public string Priority { get; set; }

    public int? TotalItems { get; set; }

    public int? TotalQuantity { get; set; }

    public int? DaysSinceOrder { get; set; }

    public string OrderStage { get; set; }
}