// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwOrderHoldManagement
{
    public Guid HoldId { get; set; }

    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string HoldType { get; set; }

    public string HoldReason { get; set; }

    public string HoldStatus { get; set; }

    public DateTime PlacedAt { get; set; }

    public DateTime? ReleasedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public int? HoldDurationHours { get; set; }

    public string CurrentHoldStatus { get; set; }

    public string UrgencyLevel { get; set; }
}