// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwPaymentAnalysis
{
    public string PaymentMethod { get; set; }

    public string PaymentProvider { get; set; }

    public string CardType { get; set; }

    public int? TotalTransactions { get; set; }

    public int? TotalOrders { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? AverageTransactionAmount { get; set; }

    public decimal? SuccessfulAmount { get; set; }

    public decimal? FailedAmount { get; set; }

    public decimal? TotalRefunded { get; set; }

    public int? SuccessfulTransactions { get; set; }

    public int? FailedTransactions { get; set; }

    public decimal? SuccessRate { get; set; }

    public decimal? AverageRiskScore { get; set; }
}