// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwPendingOrdersAction
{
    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentStatus { get; set; }

    public string FulfillmentStatus { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal TotalAmount { get; set; }

    public int? HoursPending { get; set; }

    public string RequiredAction { get; set; }

    public string PriorityLevel { get; set; }
}