// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwProductOrderPerformance
{
    public Guid ProductId { get; set; }

    public Guid? VariationId { get; set; }

    public string ProductName { get; set; }

    public string Sku { get; set; }

    public int? TotalOrders { get; set; }

    public int? TotalQuantitySold { get; set; }

    public decimal? TotalRevenue { get; set; }

    public decimal? AveragePrice { get; set; }

    public decimal? TotalDiscounts { get; set; }

    public int? CompletedOrders { get; set; }

    public int? ReturnedItems { get; set; }

    public decimal? ReturnRate { get; set; }
}