// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwRevenueAnalysis
{
    public int? OrderYear { get; set; }

    public int? OrderMonth { get; set; }

    public string MonthName { get; set; }

    public string OrderSource { get; set; }

    public string OrderType { get; set; }

    public int? TotalOrders { get; set; }

    public int? UniqueCustomers { get; set; }

    public decimal? GrossRevenue { get; set; }

    public decimal? TotalDiscounts { get; set; }

    public decimal? TotalTaxes { get; set; }

    public decimal? TotalShipping { get; set; }

    public decimal? NetRevenue { get; set; }

    public decimal? AverageOrderValue { get; set; }

    public decimal? LostRevenue { get; set; }

    public decimal? RepeatCustomerRate { get; set; }
}