// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwReturnManagement
{
    public Guid ReturnId { get; set; }

    public string ReturnNumber { get; set; }

    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string ReturnStatus { get; set; }

    public string ReturnType { get; set; }

    public string ReturnReason { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public decimal RefundAmount { get; set; }

    public string QualityCheckStatus { get; set; }

    public int? TotalReturnItems { get; set; }

    public int? TotalReturnQuantity { get; set; }

    public int? ProcessingDays { get; set; }

    public string ProcessStage { get; set; }
}