// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwShipmentTracking
{
    public Guid ShipmentId { get; set; }

    public string ShipmentNumber { get; set; }

    public Guid OrderId { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string ShipmentStatus { get; set; }

    public string CarrierName { get; set; }

    public string TrackingNumber { get; set; }

    public string TrackingUrl { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public int? DaysInTransit { get; set; }

    public string DeliveryStatus { get; set; }

    public string ShippingCity { get; set; }

    public string ShippingState { get; set; }

    public string ShippingCountry { get; set; }
}