// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class VwSubscriptionAnalysis
{
    public Guid SubscriptionId { get; set; }

    public Guid CustomerId { get; set; }

    public string CustomerEmail { get; set; }

    public string SubscriptionStatus { get; set; }

    public string Frequency { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? NextOrderDate { get; set; }

    public DateTime? LastOrderDate { get; set; }

    public int? TotalOccurrences { get; set; }

    public int CompletedOccurrences { get; set; }

    public decimal OrderAmount { get; set; }

    public decimal? TotalSubscriptionValue { get; set; }

    public int? SubscriptionAgeDays { get; set; }

    public string SubscriptionHealth { get; set; }
}