// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using OrderService.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace OrderService.Infrastructure.Persistence
{
    public partial interface IOrderServiceDbContextProcedures
    {
        Task<List<SP_AddOrderItemsResult>> SP_AddOrderItemsAsync(Guid? orderId, string orderItems, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CancelOrderResult>> SP_CancelOrderAsync(Guid? orderId, string cancellationType, string cancellationReason, Guid? cancelledBy, string cancelledByType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ConfirmOrderResult>> SP_ConfirmOrderAsync(Guid? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CreateOrderFromCartResult>> SP_CreateOrderFromCartAsync(Guid? cartId, Guid? customerId, string customerEmail, string orderSource, string billingAddress, string shippingAddress, string paymentMethod, string iPAddress, OutputParameter<Guid?> orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CreateReturnRequestResult>> SP_CreateReturnRequestAsync(Guid? orderId, Guid? customerId, string returnType, string returnReason, string returnItems, string customerComments, OutputParameter<Guid?> returnId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CreateShipmentResult>> SP_CreateShipmentAsync(Guid? orderId, Guid? warehouseId, string shippingMethod, string carrierName, string shipmentItems, OutputParameter<Guid?> shipmentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CreateSubscriptionOrderResult>> SP_CreateSubscriptionOrderAsync(Guid? orderId, Guid? customerId, string frequency, DateTime? startDate, int? totalOccurrences, Guid? paymentMethodId, OutputParameter<Guid?> subscriptionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetOrderDetailsResult>> SP_GetOrderDetailsAsync(Guid? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_MarkOrderDeliveredResult>> SP_MarkOrderDeliveredAsync(Guid? shipmentId, string deliverySignature, string deliveryProofImage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PerformFraudCheckResult>> SP_PerformFraudCheckAsync(Guid? orderId, string fraudProvider, OutputParameter<Guid?> fraudCheckId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PlaceOrderOnHoldResult>> SP_PlaceOrderOnHoldAsync(Guid? orderId, string holdType, string holdReason, Guid? placedBy, DateTime? expiresAt, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ProcessNextSubscriptionOrderResult>> SP_ProcessNextSubscriptionOrderAsync(Guid? subscriptionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ProcessPaymentResult>> SP_ProcessPaymentAsync(Guid? orderId, string paymentMethod, string paymentProvider, decimal? amount, string transactionId, string authorizationCode, string paymentGatewayResponse, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ProcessRefundResult>> SP_ProcessRefundAsync(Guid? orderId, Guid? returnId, decimal? refundAmount, string refundType, string refundMethod, string refundReason, OutputParameter<Guid?> refundId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ReleaseOrderHoldResult>> SP_ReleaseOrderHoldAsync(Guid? holdId, Guid? releasedBy, string notes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ShipOrderResult>> SP_ShipOrderAsync(Guid? shipmentId, string trackingNumber, string trackingUrl, DateTime? estimatedDeliveryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
