// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using OrderService.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace OrderService.Infrastructure.Persistence
{
    public partial class OrderServiceDbContext
    {
        private IOrderServiceDbContextProcedures _procedures;

        public virtual IOrderServiceDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new OrderServiceDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IOrderServiceDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class OrderServiceDbContextProcedures : IOrderServiceDbContextProcedures
    {
        private readonly OrderServiceDbContext _context;

        public OrderServiceDbContextProcedures(OrderServiceDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_AddOrderItemsResult>> SP_AddOrderItemsAsync(Guid? orderId, string orderItems, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "OrderItems",
                    Size = -1,
                    Value = orderItems ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_AddOrderItemsResult>("EXEC @returnValue = [dbo].[SP_AddOrderItems] @OrderId = @OrderId, @OrderItems = @OrderItems", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CancelOrderResult>> SP_CancelOrderAsync(Guid? orderId, string cancellationType, string cancellationReason, Guid? cancelledBy, string cancelledByType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CancellationType",
                    Size = 100,
                    Value = cancellationType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CancellationReason",
                    Size = 1000,
                    Value = cancellationReason ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CancelledBy",
                    Value = cancelledBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CancelledByType",
                    Size = 100,
                    Value = cancelledByType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CancelOrderResult>("EXEC @returnValue = [dbo].[SP_CancelOrder] @OrderId = @OrderId, @CancellationType = @CancellationType, @CancellationReason = @CancellationReason, @CancelledBy = @CancelledBy, @CancelledByType = @CancelledByType", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ConfirmOrderResult>> SP_ConfirmOrderAsync(Guid? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ConfirmOrderResult>("EXEC @returnValue = [dbo].[SP_ConfirmOrder] @OrderId = @OrderId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CreateOrderFromCartResult>> SP_CreateOrderFromCartAsync(Guid? cartId, Guid? customerId, string customerEmail, string orderSource, string billingAddress, string shippingAddress, string paymentMethod, string iPAddress, OutputParameter<Guid?> orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterOrderId = new SqlParameter
            {
                ParameterName = "OrderId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = orderId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CartId",
                    Value = cartId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CustomerId",
                    Value = customerId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CustomerEmail",
                    Size = 510,
                    Value = customerEmail ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OrderSource",
                    Size = 100,
                    Value = orderSource ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BillingAddress",
                    Size = -1,
                    Value = billingAddress ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ShippingAddress",
                    Size = -1,
                    Value = shippingAddress ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PaymentMethod",
                    Size = 100,
                    Value = paymentMethod ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IPAddress",
                    Size = 90,
                    Value = iPAddress ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterOrderId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CreateOrderFromCartResult>("EXEC @returnValue = [dbo].[SP_CreateOrderFromCart] @CartId = @CartId, @CustomerId = @CustomerId, @CustomerEmail = @CustomerEmail, @OrderSource = @OrderSource, @BillingAddress = @BillingAddress, @ShippingAddress = @ShippingAddress, @PaymentMethod = @PaymentMethod, @IPAddress = @IPAddress, @OrderId = @OrderId OUTPUT", sqlParameters, cancellationToken);

            orderId?.SetValue(parameterOrderId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CreateReturnRequestResult>> SP_CreateReturnRequestAsync(Guid? orderId, Guid? customerId, string returnType, string returnReason, string returnItems, string customerComments, OutputParameter<Guid?> returnId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterReturnId = new SqlParameter
            {
                ParameterName = "ReturnId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CustomerId",
                    Value = customerId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "ReturnType",
                    Size = 100,
                    Value = returnType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ReturnReason",
                    Size = 100,
                    Value = returnReason ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ReturnItems",
                    Size = -1,
                    Value = returnItems ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CustomerComments",
                    Size = -1,
                    Value = customerComments ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterReturnId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CreateReturnRequestResult>("EXEC @returnValue = [dbo].[SP_CreateReturnRequest] @OrderId = @OrderId, @CustomerId = @CustomerId, @ReturnType = @ReturnType, @ReturnReason = @ReturnReason, @ReturnItems = @ReturnItems, @CustomerComments = @CustomerComments, @ReturnId = @ReturnId OUTPUT", sqlParameters, cancellationToken);

            returnId?.SetValue(parameterReturnId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CreateShipmentResult>> SP_CreateShipmentAsync(Guid? orderId, Guid? warehouseId, string shippingMethod, string carrierName, string shipmentItems, OutputParameter<Guid?> shipmentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterShipmentId = new SqlParameter
            {
                ParameterName = "ShipmentId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = shipmentId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "WarehouseId",
                    Value = warehouseId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "ShippingMethod",
                    Size = 200,
                    Value = shippingMethod ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CarrierName",
                    Size = 200,
                    Value = carrierName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ShipmentItems",
                    Size = -1,
                    Value = shipmentItems ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterShipmentId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CreateShipmentResult>("EXEC @returnValue = [dbo].[SP_CreateShipment] @OrderId = @OrderId, @WarehouseId = @WarehouseId, @ShippingMethod = @ShippingMethod, @CarrierName = @CarrierName, @ShipmentItems = @ShipmentItems, @ShipmentId = @ShipmentId OUTPUT", sqlParameters, cancellationToken);

            shipmentId?.SetValue(parameterShipmentId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CreateSubscriptionOrderResult>> SP_CreateSubscriptionOrderAsync(Guid? orderId, Guid? customerId, string frequency, DateTime? startDate, int? totalOccurrences, Guid? paymentMethodId, OutputParameter<Guid?> subscriptionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterSubscriptionId = new SqlParameter
            {
                ParameterName = "SubscriptionId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = subscriptionId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "CustomerId",
                    Value = customerId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Frequency",
                    Size = 100,
                    Value = frequency ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StartDate",
                    Scale = 7,
                    Value = startDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "TotalOccurrences",
                    Value = totalOccurrences ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PaymentMethodId",
                    Value = paymentMethodId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterSubscriptionId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_CreateSubscriptionOrderResult>("EXEC @returnValue = [dbo].[SP_CreateSubscriptionOrder] @OrderId = @OrderId, @CustomerId = @CustomerId, @Frequency = @Frequency, @StartDate = @StartDate, @TotalOccurrences = @TotalOccurrences, @PaymentMethodId = @PaymentMethodId, @SubscriptionId = @SubscriptionId OUTPUT", sqlParameters, cancellationToken);

            subscriptionId?.SetValue(parameterSubscriptionId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_GetOrderDetailsResult>> SP_GetOrderDetailsAsync(Guid? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetOrderDetailsResult>("EXEC @returnValue = [dbo].[SP_GetOrderDetails] @OrderId = @OrderId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_MarkOrderDeliveredResult>> SP_MarkOrderDeliveredAsync(Guid? shipmentId, string deliverySignature, string deliveryProofImage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ShipmentId",
                    Value = shipmentId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "DeliverySignature",
                    Size = 400,
                    Value = deliverySignature ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DeliveryProofImage",
                    Size = 1000,
                    Value = deliveryProofImage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_MarkOrderDeliveredResult>("EXEC @returnValue = [dbo].[SP_MarkOrderDelivered] @ShipmentId = @ShipmentId, @DeliverySignature = @DeliverySignature, @DeliveryProofImage = @DeliveryProofImage", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_PerformFraudCheckResult>> SP_PerformFraudCheckAsync(Guid? orderId, string fraudProvider, OutputParameter<Guid?> fraudCheckId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterFraudCheckId = new SqlParameter
            {
                ParameterName = "FraudCheckId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = fraudCheckId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "FraudProvider",
                    Size = 200,
                    Value = fraudProvider ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterFraudCheckId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_PerformFraudCheckResult>("EXEC @returnValue = [dbo].[SP_PerformFraudCheck] @OrderId = @OrderId, @FraudProvider = @FraudProvider, @FraudCheckId = @FraudCheckId OUTPUT", sqlParameters, cancellationToken);

            fraudCheckId?.SetValue(parameterFraudCheckId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_PlaceOrderOnHoldResult>> SP_PlaceOrderOnHoldAsync(Guid? orderId, string holdType, string holdReason, Guid? placedBy, DateTime? expiresAt, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "HoldType",
                    Size = 100,
                    Value = holdType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "HoldReason",
                    Size = 1000,
                    Value = holdReason ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PlacedBy",
                    Value = placedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "ExpiresAt",
                    Scale = 7,
                    Value = expiresAt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_PlaceOrderOnHoldResult>("EXEC @returnValue = [dbo].[SP_PlaceOrderOnHold] @OrderId = @OrderId, @HoldType = @HoldType, @HoldReason = @HoldReason, @PlacedBy = @PlacedBy, @ExpiresAt = @ExpiresAt", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ProcessNextSubscriptionOrderResult>> SP_ProcessNextSubscriptionOrderAsync(Guid? subscriptionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "SubscriptionId",
                    Value = subscriptionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ProcessNextSubscriptionOrderResult>("EXEC @returnValue = [dbo].[SP_ProcessNextSubscriptionOrder] @SubscriptionId = @SubscriptionId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ProcessPaymentResult>> SP_ProcessPaymentAsync(Guid? orderId, string paymentMethod, string paymentProvider, decimal? amount, string transactionId, string authorizationCode, string paymentGatewayResponse, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "PaymentMethod",
                    Size = 100,
                    Value = paymentMethod ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PaymentProvider",
                    Size = 200,
                    Value = paymentProvider ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Amount",
                    Precision = 18,
                    Scale = 4,
                    Value = amount ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "TransactionId",
                    Size = 400,
                    Value = transactionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AuthorizationCode",
                    Size = 200,
                    Value = authorizationCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PaymentGatewayResponse",
                    Size = -1,
                    Value = paymentGatewayResponse ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ProcessPaymentResult>("EXEC @returnValue = [dbo].[SP_ProcessPayment] @OrderId = @OrderId, @PaymentMethod = @PaymentMethod, @PaymentProvider = @PaymentProvider, @Amount = @Amount, @TransactionId = @TransactionId, @AuthorizationCode = @AuthorizationCode, @PaymentGatewayResponse = @PaymentGatewayResponse", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ProcessRefundResult>> SP_ProcessRefundAsync(Guid? orderId, Guid? returnId, decimal? refundAmount, string refundType, string refundMethod, string refundReason, OutputParameter<Guid?> refundId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterRefundId = new SqlParameter
            {
                ParameterName = "RefundId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = refundId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrderId",
                    Value = orderId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "ReturnId",
                    Value = returnId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "RefundAmount",
                    Precision = 18,
                    Scale = 4,
                    Value = refundAmount ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "RefundType",
                    Size = 100,
                    Value = refundType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RefundMethod",
                    Size = 100,
                    Value = refundMethod ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RefundReason",
                    Size = 1000,
                    Value = refundReason ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterRefundId,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ProcessRefundResult>("EXEC @returnValue = [dbo].[SP_ProcessRefund] @OrderId = @OrderId, @ReturnId = @ReturnId, @RefundAmount = @RefundAmount, @RefundType = @RefundType, @RefundMethod = @RefundMethod, @RefundReason = @RefundReason, @RefundId = @RefundId OUTPUT", sqlParameters, cancellationToken);

            refundId?.SetValue(parameterRefundId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ReleaseOrderHoldResult>> SP_ReleaseOrderHoldAsync(Guid? holdId, Guid? releasedBy, string notes, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "HoldId",
                    Value = holdId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "ReleasedBy",
                    Value = releasedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Notes",
                    Size = -1,
                    Value = notes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ReleaseOrderHoldResult>("EXEC @returnValue = [dbo].[SP_ReleaseOrderHold] @HoldId = @HoldId, @ReleasedBy = @ReleasedBy, @Notes = @Notes", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ShipOrderResult>> SP_ShipOrderAsync(Guid? shipmentId, string trackingNumber, string trackingUrl, DateTime? estimatedDeliveryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ShipmentId",
                    Value = shipmentId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "TrackingNumber",
                    Size = 400,
                    Value = trackingNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TrackingUrl",
                    Size = 1000,
                    Value = trackingUrl ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EstimatedDeliveryDate",
                    Scale = 7,
                    Value = estimatedDeliveryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ShipOrderResult>("EXEC @returnValue = [dbo].[SP_ShipOrder] @ShipmentId = @ShipmentId, @TrackingNumber = @TrackingNumber, @TrackingUrl = @TrackingUrl, @EstimatedDeliveryDate = @EstimatedDeliveryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
